### ISSUE TITLE
Support for ICD9-CM Codes?

### ISSUE THREAD

**Issue by TheCedarPrince** [InPhyT/ICD_GEMs.jl#9]
Is it possible to support ICD9-CM codes?
I was just trying to use these codes from ICD9-CM and the mapping didn't produce any kind of mapping:

|ID | ICD9CM CODE | DESCRIPTION | CLASS | KIND |
|---|----------------|---------------|--------|-------|
| 44826258 | V76.2 | Screening for malignant neoplasms of cervix | Measurement | Non-Standard |
| 44828600 | V72.31 | Routine gynecological examination | Procedure | Non-Standard | 
| 44822669 | V15.89 | Other specified personal history presenting hazards to health | Observation | Non-Standard |

**Comment by InterdisciplinaryPhysicsTeam** [comment]
Hello @TheCedarPrince,

Thanks for pointing this out!

The codes you specified are actually already supported by the package, but it is required (for all codes) that you remove all punctuation before trying to convert them (we try to stick to the CDC data source as much as possible).

So in order to convert your codes, you should do:

```julia
using ICD_GEMs

I_9_sources = ["V762", "V7231", "V1589"]

I10_sources_converted_codes = execute_applied_mapping(GEM_I9_I10_dictionary, I_9_sources)
```

And this produces:

```bash
6-element Vector{String}:
 "Z124"
 "Z01411"
 "Z01419"
 "Z779"  
 "Z9284" 
 "Z9289" 
```

Note that the output has no punctuation too. 

We will update the README and the docs to better clarify it.

**Comment by TheCedarPrince** [comment]
Ah thanks!
I didn't realize that was the case - my apologies.
Great that this "just works"!
I'll close the issue!
